### ISSUE TITLE
Display Steer Axis Tilt in Degrees

### ISSUE THREAD

**Issue by sandertyu** [moorepants/BicycleParameters#47]
As I mentioned in issue #46 , there are a couple things to be solved. The method needs to be able to identify and select between 2 different cases:

1. The callback is fed a steer axis tilt in radians from the default app-data bicycles. This isn't too difficult, I can just selectively convert the value to degrees and insert it that way.
2. The callback receives that there is user edited data, and it has to receive the value in degrees, convert to radians to recalculate, and then go back into degrees like in case 1.

Functionally, we need to be able to determine whether values are being received in radians or degrees, and then do the conversion in case 2 as necessary. It may be easier to add functionality in bicycleparameters to accept degrees, but otherwise, how could we solve this?

@moorepants

**Comment by moorepants** [comment]
We should only give one option in the GUI: provide the angle in degrees. (If you really want to you can have a radio button to select whether you are entering in degrees or radians). The underlying bicycleparameters should not be changed to accept degrees.

You just need some code that does this in the app:

- pull value from gui text input box
- convert value from degrees to radians
- send converted value to bicycleparameters to create the graphs

Secondly when a bicycle is loaded from the dropdown you need to convert the value in radians to degrees for the purposes of display in the table.

**Comment by sandertyu** [comment]
Thank you, I believe I was able to implement this correctly. It is included in pull request #48, and I will close this issue and #46 once the merge is complete.
