### ISSUE TITLE
Documentation Hyperlinks 

### ISSUE THREAD

**Issue by sandertyu** [moorepants/BicycleParameters#53]
As per the suggestions from Bryn Cloud, we can go ahead and change a few things

- [x] Remove the title underline and embolden it some other way. The underline can be confused for a hyperlink
- [x] Include documentation hyperlinks for the version control box in the lower left hand corner. I'm not sure how to dynamically access these documentation pages, as I feel the url may change over time or as new versions are released. If anybody knows, please let me know.
- [x] Add a link to this repository

**Comment by moorepants** [comment]
The documentation urls will generally stay the same. I'm not sure sending them to those docs will help them use the software though. It think it is more important for use to explain what the app does and how to interact and interpret things. I will write a draft of this, just haven't had time.

**Comment by sandertyu** [comment]
> The documentation urls will generally stay the same. I'm not sure sending them to those docs will help them use the software though. It think it is more important for us to explain what the app does and how to interact and interpret things. I will write a draft of this, just haven't had time.

Yeah, I agree it won't be incredibly enlightening to read the dependency documentation. I'm not sure if you saw, but Bryn suggested it in response to my AIO for 5/14 and it's a pretty easy change. It should be just a couple html `<a>` elements.
