### ISSUE TITLE
Dash Bootstraps Overhaul

### ISSUE THREAD

**Issue by sandertyu** [moorepants/BicycleParameters#57]
The purpose here is to integrate and replace my current CSS with that already written in [Dash Bootstrap Components](https://dash-bootstrap-components.opensource.faculty.ai/docs/). The main benefit is using its layout features, so elements can be positioned easily and in ways that I don't know how to program myself. Secondly, there are a few components in the Dash Bootstrap Components library, such as [button](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/button/), which can essentially replace current components while looking a little nicer. The main goals are as follows;

- [ ] Use bootstrap layout in order to organize the web elements.
- [x] Replace a few current components with the bootstrap counter-part (this is often as easy as replacing module `html` with `dbc`).
- [x] Choose a theme for the app. Currently my favorite is [Slate](https://bootswatch.com/slate/), but the rest can be navigated through by the "Themes" toolbar at the top of the linked page.
- [x] Fit everything on to one screen page. This may be a stretch, but it should be possible, especially now that the CSS is easier to work with.

**Comment by moorepants** [comment]
This all sounds great!

**Comment by sandertyu** [comment]
Update: Still working on this. It's taking me longer than expected. The main issue is trying to sort out what parts of my css should stay, and what parts should be replaced. I also have a whole lot of html.Div elements which were necessary when I was individually styling things, but probably aren't anymore, so I have to go through and check each one of those. But I'm still in the process of coding this.

**Comment by sandertyu** [comment]
Closing this issue to make additional ones for more specific issues.
