### ISSUE TITLE
Layout isn't good for the mass center and inertia radio buttons on narrow screen

### ISSUE THREAD

**Issue by moorepants** [moorepants/BicycleParameters#59]
![Selection_714](https://user-images.githubusercontent.com/276007/83839160-15e4ea00-a6b0-11ea-8c8d-ce56edb8836a.png)

**Comment by sandertyu** [comment]
Got it. It's an issue with incomplete bootstraps implementation, which is still on the way.

**Comment by sandertyu** [comment]
Closing this issue because the layout doesn't look like this at all anymore
