### ISSUE TITLE
Possible OS version incompatibility. 

### ISSUE THREAD

**Issue by sandertyu** [moorepants/BicycleParameters#60]
Running from windows terminal on my system, the cycle app appears as so:
![windows](https://user-images.githubusercontent.com/59950537/84605719-5680f800-ae54-11ea-9647-f73c189dc944.PNG)
It also does that jarring screen move effect whenever the eigenvalue slider is change. We had fixed this before on past versions. You can also see that the eigenvalue slider is not readable, which is what I had mentioned in the pull request.

However, when I run through my linux subshell, the app appears correctly, the same as it does on the live version. Here is what that looks like;
![linux](https://user-images.githubusercontent.com/59950537/84605740-8b8d4a80-ae54-11ea-8ca7-65eb27a4935a.PNG)

I've done `conda update --all`, and each of my packages should be equivalent across my windows and linux versions of python. I have no idea what could be causing this. For now, I'll just run through the linux subshell.

**Comment by moorepants** [comment]
I doubt this is an OS difference, as it has little effect on rendering things in the browser. It is more likely a mismatch in dependencies (or differences in browsers).

Setup a .condarc file and write this in it:

```
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

This will install packages from the conda forge channel first and then default. Conda forge has the most up-to-date packages. After you do this, run `conda update --all` again.

**Comment by moorepants** [comment]
The info I gave you is from here: https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

**Comment by sandertyu** [comment]
I did that but now I get a whole host of errors when I try to install anything. This has happened before, and my condarc was already set with those settings you gave, but when I run these commands, it reverts back to an putting `-defaults` first, and then `conda-forge`, despite manually setting `conda-forge` first.  The errors are the following;

`(base) C:\Users\xyzasdf\Desktop\bike-lab\BicycleParameters>conda update --all`
`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`
`Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed`
`Solving environment: failed`

and similarly;

`(base) C:\Users\xyzasdf\Desktop\bike-lab\BicycleParameters>conda install numpy`
`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`

I used numpy just as a test, based on suggestions from [here](https://stackoverflow.com/questions/51266535/conda-returns-solving-environment-failed). I'm going to try running through environments instead. I had refrained before because it doesn't install all those basic packages like numpy and matplotlib by default when I create an environment, and it's annoying to install them all manually.

**Comment by sandertyu** [comment]
Okay, creating a specific conda environment and running from within there solved the issue. Not sure how to fix my root environment (it is certainly some sort of package conflict causing the issue), but this will work from now on. I'll add default packages through my .condarc file. Closing the issue.

**Comment by moorepants** [comment]
I can help you debug the root environment in a call. Weird that it is so messed up on initial install of conda.

**Comment by sandertyu** [comment]
> I can help you debug the root environment in a call. Weird that it is so messed up on initial install of conda.

Sure that would be good. I may be partially to blame for installing all the app dependencies in my root rather than a new environment, I didn't expect it to go bad so soon though.

**Comment by moorepants** [comment]
I use the root environment for this app and it works fine. Something weird must have happened.
