### ISSUE TITLE
Datatable Selected Cell Highlighting and Text Color

### ISSUE THREAD

**Issue by sandertyu** [moorepants/BicycleParameters#68]
When a cell is selected and hovered over, it appears as so;

![hover-over](https://user-images.githubusercontent.com/59950537/86410671-0c7b7d00-bc70-11ea-824c-3f12236ff5e8.png)

However, when the cell is selected and you do not hover over it, the pink background disappears and the text becomes very difficult to read 

![selected](https://user-images.githubusercontent.com/59950537/86410701-1d2bf300-bc70-11ea-8df5-0c88f4570ffc.png)

The culprit CSS is right here. If the color value on the right where the arrow points is changed, then the text color will change. I've tried multiple ways of directly putting this CSS into our styles.css file in assets, but it does not good.

![CSS](https://user-images.githubusercontent.com/59950537/86411075-e2768a80-bc70-11ea-8970-3d66ef6dfe7d.PNG)

My goal is to remove the pink background, leave the border, and have the text be white and legible as it normally is. It would look like this. It is much nicer this way because there isn't currently a method (as far as I know) to unselect a cell, so the default pink border is far less obnoxious than the entire cell background changing.

![goal](https://user-images.githubusercontent.com/59950537/86411088-e9050200-bc70-11ea-8e0c-256621e67d35.png)

In the Dash documentation, in the section about the [dark theme](https://dash.plotly.com/datatable/style), when you click on the cells of their table the text color does not change. My dark mode styling is identical. I guessed that the bootstrap theme was overriding something, but changing the theme does not fix the issue. The text color changing when a cell is selected also existed before bootstraps was even implemented within the app, so there's something hidden going on.

**Comment by rrryy39** [comment]
When I use the them rather than CYBORG, it seemed to solved the issue

**Comment by moorepants** [comment]
What is CYBORG?

**Comment by rrryy39** [comment]
I mistype 'theme' to 'them'
it is a theme, it is in the cycle_app.py line 67
i tried BOOTSTRAP and it worked fine
![cyborg](https://user-images.githubusercontent.com/72050785/95175599-8f7d0980-0770-11eb-9fdf-07ae5f9f4dde.PNG)

**Comment by moorepants** [comment]
Are you suggesting to change the theme?

**Comment by rrryy39** [comment]
I tried multiple way of fixing, like override the existing style.css file but it did not work. I think changing the theme is the best way to go. But If you don't want the theme to be changed, I will do some more research tomorrow and try to keep the theme.

**Comment by moorepants** [comment]
Please paste in an image of the app using the different theme you propose.

**Comment by moorepants** [comment]
Paste in images of the cell colors too like above.

**Comment by rrryy39** [comment]
The overall background is white and The text color and the table background can be changed as well
![Theme](https://user-images.githubusercontent.com/72050785/95247592-e8798b80-07ca-11eb-8338-ef04b54d3fe2.PNG)

**Comment by moorepants** [comment]
Noah (last student) spend some time getting the current theme correct, so I think we should stick with that. If you are having trouble overriding css, you need to show me what you are doing and I can give some advice.

**Comment by sandertyu** [comment]
The goal of this PR was the remove that whiteish/pink background that you see behind the `0.9` table entry that you have selected there. The pink cell selected background itself isn't too much of a problem (altho it's a bit of an eyesore), but when you have the cell selected and no longer hover your mouse over it, the background dulls and the numbers are hard to read as you see below;

![dull background](https://user-images.githubusercontent.com/59950537/86410701-1d2bf300-bc70-11ea-8df5-0c88f4570ffc.png)

Notice the difference here, which is the desired look;

![no pink](https://user-images.githubusercontent.com/59950537/86411088-e9050200-bc70-11ea-8e0c-256621e67d35.png)

**Comment by rrryy39** [comment]
![sell](https://user-images.githubusercontent.com/72050785/97403588-f1351d00-18b1-11eb-91f0-ec91dee76da1.PNG)
Hello, professor Moore, I now can change the back ground color to white when selected, is this helpful?

**Comment by moorepants** [comment]
That looks good.

**Comment by moorepants** [comment]
Fixed in #81
