### ISSUE TITLE
Release version 1.1.0

### ISSUE THREAD

**Issue by moorepants** [moorepants/BicycleParameters#94]
Things that need to be done:

- [x] rename `cycle_app.py` to `app.py`.
- [x] Add entry point for the app.
- [x] get it working on Python 3.10 (including Yeadon)
- [x] Autodoc the new models (or make them private for now)
- [x] Complete all docstrings of the new modules
- [x] Decide to lock in the new module API or make the modules private for now
- [x] Improve and update the app colophon

**Comment by TJStienstra** [comment]
#99 should also be fixed first.

**Comment by moorepants** [comment]
Plotly should be an optional dependency only for running the app.
