### ISSUE TITLE
Small documentation mistakes

### ISSUE THREAD

**Issue by tjstienstra** [moorepants/BicycleParameters#98]
Thought lets collect small documentation mistakes while going though the documentation:
- In [example.rst](https://github.com/moorepants/BicycleParameters/blame/master/docs/examples.rst#L183) `>>> bicycle.parameters['Benchmark']['mB] = 50.` misses an `'`.
- In [data.rst](https://github.com/moorepants/BicycleParameters/blame/master/docs/data.rst#L287) it says two times `<rider name><bicycle name>YeadonCFG.txt`. The second should be `<rider name><bicycle name>YeadonMeas.txt` if I'm not mistaken.
- The reference to the [raw data sheet](http://bit.ly/jIeKKB) reference in [data.rst](https://github.com/moorepants/BicycleParameters/blame/master/docs/data.rst#L164) does not work anymore.

**Comment by moorepants** [comment]
> The reference to the [raw data sheet](http://bit.ly/jIeKKB) reference in [data.rst](https://github.com/moorepants/BicycleParameters/blame/master/docs/data.rst#L164) does not work anymore.

Suprisingly it seems to work for me.
