### ISSUE TITLE
Plotly is not in the requirements

### ISSUE THREAD

**Issue by tjstienstra** [moorepants/BicycleParameters#99]
When installing the development version of this repo, I noticed that `plotly` is currently not in the requirements, while it is being used.

**Comment by TJStienstra** [comment]
It is possible that one should also add `pandas` to the requirements. `plotly` seems to require it, but does not install it automatically?

I got the following error: `ImportError: Plotly express requires pandas to be installed.`

**Comment by moorepants** [comment]
pandas and plotly should be optional dependencies only needed for the app to run.

**Comment by TJStienstra** [comment]
`import plotly.express as px` is in `main.py`, so you kind of always need it now. It is used in `_plot_bicycle_geometry_plotly` and `_plot_eigenvalues_vs_speed_plotly`

**Comment by moorepants** [comment]
That needs to be moved out to another file.

**Comment by moorepants** [comment]
Fix proposed in #100.
